Resources:
  TeemOpsGroup:
    Type: "AWS::IAM::Group"
    Properties:
        GroupName: "teemops-manage"
  TeemOpsPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "TeemopsSTSAssume"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "sts:AssumeRole"
            Resource: "*"
      Groups: 
        - 
          Ref: "TeemOpsGroup"