Resources:
  TeemOpsGroup:
    Type: "AWS::IAM::Group"
    Properties:
        GroupName: "teemops-root-users"
        Path: '/'
  TeemOpsRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "teemops-root"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  TeemOpsInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Roles:
          - !Ref TeemOpsRole
        InstanceProfileName: "TeemopsInstanceProfile"
  TeemOpsPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "TeemopsSTSAssume"
      Roles:
        - !Ref TeemOpsRole
      Groups:
        - !Ref TeemOpsGroup
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "sts:AssumeRole"
            Resource: "*"
  TeemOpsAppPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "TopsAppTasks"
      Roles:
        - !Ref TeemOpsRole
      Groups:
        - !Ref TeemOpsGroup
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "sns:*"
              - "cloudformation:*"
              - "SQS:*"
              - "dynamoDb:*"
              - "s3:*"
              - "events:*"
              - "cloudwatch:*"
            Resource: "*"
  TeemOpsEventBusPolicy: 
    Type: AWS::Events::EventBusPolicy
    Properties: 
        Action: "events:PutEvents"
        Principal: "*"
        StatementId: "TopsAllowCrossAccountEvents"

